#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

((EUID)) && exec sudo -- "$0" "$@"

packageName="$1"
shift

failinstall() {
    die "ERROR: Could not find or install $1."
}

cd "$(getSystemTempLocation)"

if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z $ebs_loc ]]; then
    git clone https://github.com/ethus3h/ember_bash_setup
    pushd ember_bash_setup
    make autodep
    make
    make install
    popd
    rm -r ember_bash_setup
fi

#### End of automatic dependency installation install script template ####

if ! cryst_loc="$(type -P "crystallize")" || [[ -z $cryst_loc ]]; then
    git clone https://github.com/ethus3h/crystallize
    pushd crystallize
    make autodep
    make
    make install
    popd
    rm -r crystallize
fi

if ! npm_loc="$(type -P "npm")" || [[ -z $npm_loc ]]; then
    if ! apt install nodejs &> /dev/null; then
        apt-get install nodejs &> /dev/null || failinstall "nodejs"
    fi
fi

npm install --global postcss-cli autoprefixer html-minifier html5-tidy minifier || failinstall "npm packages"
cpan -f -i HTML::GenToc || failinstall "HTML::GenToc"

if ! npm_loc="$(type -P "npm")" || [[ -z $npm_loc ]]; then
    failinstall "python2"
fi
