#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
#set -x

((EUID)) && exec sudo -- "$0" "$@"

failinstall() {
    echo "ERROR: Could not find or install $1."
    exit 1
}

if [[ -n "$TMPDIR" ]]; then
    cd "$TMPDIR"
else
    cd "/tmp"
fi

if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z $ebs_loc ]]; then
    git clone https://github.com/ethus3h/crystallize
    pushd crystallize
    make autodep
    make
    make install
    popd
    rm -r crystallize
fi

if ! npm_loc="$(type -P "npm")" || [[ -z $npm_loc ]]; then
    if ! apt install nodejs &> /dev/null; then
        apt-get install nodejs &> /dev/null || failinstall "nodejs"
    fi
fi

npm install --global postcss-cli autoprefixer html-minifier html5-tidy minifier || failinstall "npm packages"
cpan -f -i HTML::GenToc || failinstall "HTML::GenToc"

if ! npm_loc="$(type -P "npm")" || [[ -z $npm_loc ]]; then
    failinstall "python2"
fi
