#!/bin/bash
echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
crystallizeDestdir="$1"
crystallizePrefix="$2"
crystallizeCapPrefix="$3"
crystallizeExecPrefix="$4"
crystallizeBindir="$5"
crystallizeDatarootdir="$6"
crystallizeDatadir="$7"
crystallizeSysconfdir="$8"
crystallizeSharedstatedir="$9"
if ! [ -n "$crystallizePrefix" ]; then
    if ! [ -n "$crystallizeCapPrefix" ]; then
        crystallizePrefix="$crystallizeDestdir"/usr/local
    else
        crystallizePrefix="$crystallizeCapPrefix"
    fi
fi
echo "crystallizePrefix: $crystallizePrefix"
if ! [ -n "$crystallizeExecPrefix" ]; then
    crystallizeExecPrefix="$crystallizePrefix"
fi
echo "crystallizeExecPrefix: $crystallizeExecPrefix"
if ! [ -n "$crystallizeBindir" ]; then
    crystallizeBindir="$crystallizeExecPrefix"/bin
fi
echo "crystallizeBindir: $crystallizeBindir"
if ! [ -n "$crystallizeDatarootdir" ]; then
    crystallizeDatarootdir="$crystallizePrefix"/share
fi
echo "crystallizeDatarootdir: $crystallizeDatarootdir"
if ! [ -n "$crystallizeDatadir" ]; then
    crystallizeDatadir="$crystallizeDatarootdir"
fi
echo "crystallizeDatadir: $crystallizeDatadir"
if ! [ -n "$crystallizeSysconfdir" ]; then
    crystallizeSysconfdir="$crystallizePrefix"/etc
fi
echo "crystallizeSysconfdir: $crystallizeSysconfdir"
if ! [ -n "$crystallizeSharedstatedir" ]; then
    crystallizeSharedstatedir="$crystallizePrefix"/var
fi
echo "crystallizeSharedstatedir: $crystallizeSharedstatedir"
export crystallizeBindir
export crystallizeSharedstatedir
export crystallizeSysconfdir
crystallizeBindirEsc="$(perl -0777 -e 'print(quotemeta($ENV{crystallizeBindir}))')"
echo "crystallizeBindirEsc: $crystallizeBindirEsc"
crystallizeSharedstatedirEsc="$(perl -0777 -e 'print(quotemeta($ENV{crystallizeSharedstatedir}))')"
echo "crystallizeSharedstatedirEsc: $crystallizeSharedstatedirEsc"
crystallizeSysconfdirEsc="$(perl -0777 -e 'print(quotemeta($ENV{crystallizeSysconfdir}))')"
echo "crystallizeSysconfdirEsc: $crystallizeSysconfdirEsc"
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/decrystallize
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/quickliquid
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/crystallize-update
perl -0777 -p -i -e "s/\/usr\/local\/etc/$crystallizeSysconfdirEsc/g" scripts/crystallize-getconf
perl -0777 -p -i -e "s/\/usr\/local\/etc/$crystallizeSysconfdirEsc/g" scripts/crystallize-logsession
perl -0777 -p -i -e "s/\/usr\/local\/var/$crystallizeSharedstatedirEsc/g" support/crystallize.conf
mkdir -p "$crystallizeBindir"
chmod +x scripts/*
cp scripts/* "$crystallizeBindir/"
mkdir -p "$crystallizeSysconfdir"
cp -v support/crystallize.conf "$crystallizeSysconfdir/"
mkdir -p "$crystallizeSharedstatedir"/crystallize
