#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

#NOTE: MAINTENANCE: Manual error printing
if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
    printf '%b' '\033[1;31m' >&2
    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
    printf '%b' '\033[0m' >&2
    exit 1
fi

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

packageName="$1"
shift

skipConfigFile="false"
if [[ "$1" == "--skip-config-file" ]]; then
    skipConfigFile="true"
    shift
fi

source support/getDirs

# Done setting up variables, now install the files

mkdir -p "$emberEmberdir"
mkdir -p "$emberBindir"

if [[ -e data ]]; then
    mkdir -p "$emberDatadir/$packageName"
    cp -r data "$emberDatadir/$packageName/"
fi

if [[ -e scripts ]]; then
    mkdir -p "$emberBindir"
    chmod +x scripts/*
    find scripts -maxdepth 1 -type f -exec cp {} "$emberBindir/" \;
fi

if [[ -e docs/futuramerlin-web-toolkit-output ]]; then
    mkdir -p "$emberDatadir/doc/$packageName"
    cp -r docs/futuramerlin-web-toolkit-output/* "$emberDatadir/doc/$packageName/"
fi

if [[ -e "support/$packageName.conf" ]]; then
    if [[ "$skipConfigFile" == "false" ]]; then
        mkdir -p "$emberSysconfdir"
        cp -v "support/$packageName.conf" "$emberSysconfdir/"
    fi
fi

#### End of Makefile install script template ####

# Any extra installation logic goes here.

if [[ -e scripts ]]; then
    mkdir -p "$emberBindir"
    chmod +x scripts/*
    find scripts -maxdepth 1 -type f -exec cp {} "$emberBindir/" \;
fi

mkdir -p "$emberSharedstatedir"/futuramerlin-web-toolkit
mkdir -p "$emberDatadir/futuramerlin-web-toolkit"
cp -v support/assets/m.css "$emberPrefix"
cp -rv support/assets "$emberDatadir/futuramerlin-web-toolkit/"
