#!/bin/bash
#Requires html-minifier: https://www.npmjs.com/package/html-minifier
#Requires html5-tidy: https://github.com/htacg/tidy-html5
#Requires minifier: https://www.npmjs.com/package/minifier
#Requires hypertoc: sudo cpan -f -i HTML::GenToc
#Requires autoprefixer: sudo npm install --global postcss-cli autoprefixer

cd ./source
./build
