#!/bin/bash
#Futuramerlin Web Toolkit build script
#Version:
export futuramerlinWebToolkitVersion='2.0.1'

shopt -s extglob
set -e

echo "Preparing environment..."
futuramerlinWebToolkitSiteName=$(sed '1q;d' "$HOME"/.futuramerlin-web-toolkit.cfg)
futuramerlinWebToolkitWordPressLocation=$(sed '2q;d' "$HOME"/.futuramerlin-web-toolkit.cfg)
futuramerlinWebToolkitLocalInstallationConfig=$(sed '3q;d' "$HOME"/.futuramerlin-web-toolkit.cfg)
futuramerlinWebToolkitLocalInstallationEnabled=false
if [[ $futuramerlinWebToolkitLocalInstallationConfig == "enableLocalInstallation" ]]; then
    futuramerlinWebToolkitLocalInstallationEnabled=true
fi
rm -rf ./futuramerlin-web-toolkit-output
mkdir -p "futuramerlin-web-toolkit-content/content"
mkdir "futuramerlin-web-toolkit-content/scripts"
find . -maxdepth 1 -name "*" ! -path . ! -path ./futuramerlin-web-toolkit-content -exec cp -r {} ./futuramerlin-web-toolkit-content/content/ \;
mkdir ./source
mv ./futuramerlin-web-toolkit-content/* ./source
rm -r ./futuramerlin-web-toolkit-content
git clone https://github.com/ethus3h/futuramerlin-web-toolkit.git
mkdir built
mv ./futuramerlin-web-toolkit/assets/* ./futuramerlin-web-toolkit/assets/.[^.]* ./built/
cp -r ./built ./source/assets
mv ./futuramerlin-web-toolkit/futuramerlin-web-toolkit-build-page ./source/scripts/build-page
rm -rf ./futuramerlin-web-toolkit
cd ./source

echo "Environment ready; building site..."
#The parentheses make the block run in a subshell, I think. I'm not sure why I have them, or what effect they have.
(
    cd "content" || exit
    if [ -f .futuramerlin-web-toolkit/pre-build-hooks ]; then
        echo "Beginning pre-build-hooks..."
        ./.futuramerlin-web-toolkit/pre-build-hooks || echo "WARNING! pre-build-hooks failed."
        echo "Done pre-build-hooks."
    fi
    traversedirectory() {
        echo "Entered directory $1..."
        #Iterate over the contents of the directory at $1
        shopt -s dotglob
        for i in "$1"/*; do
            mkdir -p "../../built/$1"
            if [[ -d "$i" ]]; then
                if [[ "$i" != @(.|..|./.git|./.futuramerlin-web-toolkit) ]]; then
                    echo "Entering directory $i..."
                    traversedirectory "$i"
                fi
            else
                if [[ "$i" =~ \.htm ]]; then
                    echo "Building page: $i"
                    ../scripts/build-page "$i"
                else
                    echo "Copying content asset: $i"
                    cp "$i" "../../built/$i"
                fi
            fi
        done
        shopt -u dotglob
    }
    traversedirectory "."
    if [ -f .futuramerlin-web-toolkit/post-build-hooks ]; then
        echo "Beginning post-build-hooks..."
        ./.futuramerlin-web-toolkit/post-build-hooks || echo "WARNING! post-build-hooks failed."
        echo "Done post-build-hooks."
    fi
)

echo "Processing CSS..."
postcss --use postcss-cssnext --postcss-cssnext.browsers "> 1%, iOS > 0, ie >= 5, last 3 versions, Firefox ESR, Firefox >= 1" -o "../built/m.css" "../built/m.css"
tr '\n' ' ' < "../built/m.css" > "../built/1.tmp"
tr '\t' ' ' < "../built/1.tmp" > "../built/2.tmp"
tr '\r' ' ' < "../built/2.tmp" > "../built/3.tmp"
tr -s " " < "../built/3.tmp" > "../built/m.css"
minify --no-comments -o "../built/m.css" "../built/m.css" > /dev/null
rm ../built/*.tmp
cd ..

echo "Finishing up..."
rm ./built/1_start.html ./built/2_end.html
mv ./built/wordpress-integration "./built/$futuramerlinWebToolkitWordPressLocation"
if [[ $futuramerlinWebToolkitLocalInstallationEnabled ]]; then
    sudo cp "./built/m.css" "/m.css"
fi
mv ./built ./futuramerlin-web-toolkit-output
mv ./source ./futuramerlin-web-toolkit-content
rm -rf ./futuramerlin-web-toolkit-content

#Clear the screen
printf "\033c"

echo "Done! The finished Web site is in:"
echo "./futuramerlin-web-toolkit-output"
