#!/bin/bash
#Futuramerlin Web Toolkit build script

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

shopt -s extglob

echo "Preparing environment..."
mkdir output
cd output
cp -r ./assets/* ./assets/.[^.]* .
echo "Environment ready; building site..."

#The parentheses make the block run in a subshell, I think. I'm not sure why, or what effect this has.
(
	cd "content" || exit
	traversedirectory() {
		echo "Entered directory $1..."
        #Iterate over the contents of the directory at $1 (doesn't include dotfiles unless the dotglob option is enabled)
		for i in "$1"/*; do
			mkdir -p "../../built/$1"
			if [[ -d "$i" ]]; then
				if ! [[ "$i" == "." ]]; then
					if ! [[ "$i" == ".." ]]; then
						echo "Entering directory $i..."
						traversedirectory "$i"
					fi
				fi
			else
				if [[ "$i" =~ \.htm ]]; then
					echo "Building page: $i"
					../scripts/build-page "$i"
				else
					echo "Copying content asset: $i"
					cp "$i" "../../built/$i"
				fi
			fi
		done
	}
	traversedirectory "."
)
echo "Processing CSS..."
cp "./assets/m.css" "../built/m.css"
postcss --use postcss-cssnext --postcss-cssnext.browsers "> 1%, iOS > 0, ie >= 5, last 3 versions, Firefox ESR, Firefox >= 1" -o "../built/m.css" "../built/m.css"
tr '\n' ' ' < "../built/m.css" > "../built/1.tmp"
tr '\t' ' ' < "../built/1.tmp" > "../built/2.tmp"
tr '\r' ' ' < "../built/2.tmp" > "../built/3.tmp"
tr -s " " < "../built/3.tmp" > "../built/m.css"
minify --no-comments -o "../built/m.css" "../built/m.css" > /dev/null
rm ../built/*.tmp
cp "../built/m.css" "/m.css"
echo "Done!"
