#!/bin/bash
#Futuramerlin Web Toolkit build script
#Version:
export futuramerlinWebToolkitVersion='2.0'

shopt -s extglob
set -e

echo "Preparing environment..."
futuramerlinWebToolkitSiteName=$(sed '1q;d' "$HOME"/.futuramerlin-web-toolkit.cfg)
futuramerlinWebToolkitLocalInstallationConfig=$(sed '2q;d' "$HOME"/.futuramerlin-web-toolkit.cfg)
futuramerlinWebToolkitLocalInstallationEnabled=false
if [[ $futuramerlinWebToolkitLocalInstallationConfig == "enableLocalInstallation" ]]; then
    futuramerlinWebToolkitLocalInstallationEnabled=true
fi
mkdir -p "futuramerlin-web-toolkit-content/content"
mkdir "futuramerlin-web-toolkit-content/scripts"
find . -maxdepth 1 -name "*" ! -path . ! -path ./futuramerlin-web-toolkit-content -exec mv {} ./futuramerlin-web-toolkit-content/content/ \;
mkdir ./source
mv ./futuramerlin-web-toolkit-content/* ./source
rm -r ./futuramerlin-web-toolkit-content
git clone https://github.com/ethus3h/futuramerlin-web-toolkit.git
mkdir built
mv ./futuramerlin-web-toolkit/assets/* ./futuramerlin-web-toolkit/assets/.[^.]* ./built/
cp -r ./built ./source/assets
mv ./futuramerlin-web-toolkit/futuramerlin-web-toolkit-build-page ./source/scripts/build-page
rm -rf ./futuramerlin-web-toolkit
cd ./source

echo "Environment ready; building site..."
#The parentheses make the block run in a subshell, I think. I'm not sure why I have them, or what effect they have.
(
	cd "content" || exit
	traversedirectory() {
		echo "Entered directory $1..."
        #Iterate over the contents of the directory at $1 (doesn't include dotfiles unless the dotglob option is enabled)
		for i in "$1"/*; do
			mkdir -p "../../built/$1"
			if [[ -d "$i" ]]; then
				if ! [[ "$i" == "." ]]; then
					if ! [[ "$i" == ".." ]]; then
						echo "Entering directory $i..."
						traversedirectory "$i"
					fi
				fi
			else
				if [[ "$i" =~ \.htm ]]; then
					echo "Building page: $i"
					../scripts/build-page "$i"
				else
					echo "Copying content asset: $i"
					cp "$i" "../../built/$i"
				fi
			fi
		done
	}
	traversedirectory "."
)

echo "Processing CSS..."
postcss --use postcss-cssnext --postcss-cssnext.browsers "> 1%, iOS > 0, ie >= 5, last 3 versions, Firefox ESR, Firefox >= 1" -o "../built/m.css" "../built/m.css"
tr '\n' ' ' < "../built/m.css" > "../built/1.tmp"
tr '\t' ' ' < "../built/1.tmp" > "../built/2.tmp"
tr '\r' ' ' < "../built/2.tmp" > "../built/3.tmp"
tr -s " " < "../built/3.tmp" > "../built/m.css"
minify --no-comments -o "../built/m.css" "../built/m.css" > /dev/null
rm ../built/*.tmp
cd ..

echo "Finishing up..."

if [[ $futuramerlinWebToolkitLocalInstallationEnabled ]]; then
    sudo cp "./built/m.css" "/m.css"
fi
mv ./built ./futuramerlin-web-toolkit-output
mv ./source ./futuramerlin-web-toolkit-content
find ./futuramerlin-web-toolkit-content -maxdepth 1 -name "*" ! -path . -exec mv {} . \;
rm -r ./futuramerlin-web-toolkit-content

#Clear the screen
printf "\033c"

echo "Done! The finished Web site is in:"
echo "./futuramerlin-web-toolkit-output"
