#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Convert a fmwtk simple-format page (*.ftm) to the more html-like fmwtk format; other files will be returned as-is
# ftm = Futuramerlin-web-Toolkit Markup
# Usage: fmwtk-convpage [page].ftm [output-file]

infile="$1"
outfile="$2"
stdout="false"
extension="${infile//*.}"

if [[ -z "$outfile" ]]; then
    outfile="-"
fi
if [[ "-" == "$outfile" ]]; then
    outfile="$(tempFile)"
    stdout="true"
fi

cp "$infile" "$outfile"

if [[ "ftm" == "$extension" ]]; then
    echo >> "$outfile" # make sure there's a blank line at the end to use for detecting closing tags
    prevLine=""
    prevLineSpaces=""
    prevLineWithoutSpaces=""
    prevLineIsListItem="false"
    prevLineSpacesCount="0"
    { while IFS= read -r thisLine; do
        thisLineSpaces="$(perl -0777 -p -i -e 's/^(\s*)([^\s].*)$/\1/g' 2>/dev/null <<< "$thisLine")"
        thisLineWithoutSpaces="$(perl -0777 -p -i -e 's/^(\s*)([^\s].*)$/\2/g' 2>/dev/null <<< "$thisLine")"
        thisLineIsListItem="false"
        [[ "$thisLineWithoutSpaces" =~ ^-\  ]] && thisLineIsListItem="ul"
        [[ "$thisLineWithoutSpaces" =~ ^\#\  ]] && thisLineIsListItem="ol"
        thisLineSpacesCount="$(wc -c <<< "$thisLineSpaces")"
        thisLineSpacesCount=$(( thisLineSpacesCount - 1 ))
        if [[ "$prevLineSpacesCount" -lt "$thisLineSpacesCount" ]] || [[ "false" == "$prevLineIsListItem" ]]; then
            # This line has more spaces, or the previous line was not a list item, so it could be a list beginning
            processed="$(perl -0777 -p -i -e '
                s/^('"$thisLineSpaces"')- ([^\n]*)/\1<ul>\n\1    <li>\2<\/li>/m; # ul start tags
                s/^('"$thisLineSpaces"')# ([^\n]*)/\1<ol>\n\1    <li>\2<\/li>/m; # ol start tags
            ' 2>/dev/null <<< "$thisLine")"
            #echo "Input:$thisLine:Processed:$processed:PLS:$prevLineSpaces:TLS:$thisLineSpaces:"
        elif [[ "$prevLineSpacesCount" -gt "$thisLineSpacesCount" ]]; then
            # It has fewer spaces, so it could be a list end
            processed="$(perl -0777 -p -i -e '
                s/^('"$thisLineSpaces"')- ([^\n]*)/\1    <\/ul>\n\1<li>\2<\/li>/m; # ul end tags in list
                s/^('"$thisLineSpaces"')# ([^\n]*)/\1    <\/ol>\n\1<li>\2<\/li>/m; # ol end tags in list
            ' 2>/dev/null <<< "$thisLine")"
        elif [[ "$prevLineSpacesCount" -gt "$thisLineSpacesCount" ]]; then
            # The previous line was a list item, so it could be a list end (but is not ending within a list)
            processed="$(perl -0777 -p -i -e '
                s/^('"$thisLineSpaces"')([^-][^ ][^\n]*\n|\n)/\1<\/ul>\2/cgm; # ul end tags
                s/^('"$thisLineSpaces"')([^#][^ ][^\n]*\n|\n)/\1<\/ul>\2/cgm; # ol end tags
            ' 2>/dev/null <<< "$thisLine")"
        else
            # The previous line was a list item, so it could be a list end (but is not ending within a list)
            processed="$(perl -0777 -p -i -e '
                s/^('"$thisLineSpaces"')([^-][^ ][^\n]*\n|\n)/\1<\/ul>\2/cgm; # ul end tags
                s/^('"$thisLineSpaces"')([^#][^ ][^\n]*\n|\n)/\1<\/ul>\2/cgm; # ol end tags
            ' 2>/dev/null <<< "$thisLine")"
        fi
        echo ":$processed:"
#        echo "$thisLineSpaces" | wc -c
#        if [[ $currentPageLine]]
 #       perl -p -i -e 
        prevLine="$thisLine"
        prevLineSpaces="$thisLineSpaces"
        prevLineWithoutSpaces="$thisLineWithoutSpaces"
        prevLineIsListItem="$thisLineIsListItem"
        prevLineSpacesCount="$thisLineSpacesCount"
    done < "$outfile"; } | sponge "$outfile"
#     perl -0777 -p -i -e '
#         s/^(\s*)\@1 ([^\n]*)\n/\1<h1>\2<\/h1>\n/gm; # headers
#         s/^(\s*)\@2 ([^\n]*)\n/\1<h2>\2<\/h2>\n/gm;
#         s/^(\s*)\@3 ([^\n]*)\n/\1<h3>\2<\/h3>\n/gm;
#         s/^(\s*)\@4 ([^\n]*)\n/\1<h4>\2<\/h4>\n/gm;
#         s/^(\s*)\@5 ([^\n]*)\n/\1<h5>\2<\/h5>\n/gm;
#         s/^(\s*)\@6 ([^\n]*)\n/\1<h6>\2<\/h6>\n/gm;
#         #s/^(\s*[^-\n]*\n)(\s*- )/\1\n<ul>\2/gm; # ul start tags
#         #s/^(\s*[^#\n]*\n)(\s*# )/\1\n<ol>\2/gm; # ol start tags
#         #s/^(\s*- [^\n]*\n)(\s*[^-][^ ][^\n]*\n)/\1\2<\/ul>\n/gm; # ul end tags
#         #s/^(\s*# [^\n]*\n)(\s*[^#][^ ][^\n]*\n)/\1\2<\/ol>\n/gm; # ol end tags
#         s/^(\s*)- ([^\n]*)\n/\1<li>\2<\/li>\n/gm; # li tags in ul
#         s/^(\s*)# ([^\n]*)\n/\1<li>\2<\/li>\n/gm; # li tags in ol
#         s/^(\s*)([^<\n\s][^\n]*)\n/\1<p>\2<\/p>\n/gm; # paragraph tags
#         ' "$outfile" || die "Substitution failed"
fi

if [[ "true" == "$stdout" ]]; then
    cat "$outfile"
fi
