#!/bin/bash
# Futuramerlin Web Toolkit Content Generator: Static copy of page
set -e
(
    cd content
    set +e
    rm -r ./*
    if wget --adjust-extension -p -e robots="off" "$@"; then
        echo "(Done getting static page(s))"
    else
        echo "WARNING: Could not download static page(s), using cached copy"
        rsync -av --checksum --progress --no-i-r ../.futuramerlin-web-toolkit/gen/static/content .
    fi
)
set -e
rsync -av --checksum --progress --no-i-r content ../.futuramerlin-web-toolkit/gen/static/
