#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

#FIXME
# Futuramerlin Web Toolkit Content Generator: Static copy of page
set -e
mkdir -pv content
(
    cd content
    set +e
    if wget --adjust-extension -p -e robots="off" --warc-file="futuramerlin-web-toolkit.static-oneshot.warc.gz" "$@"; then
        echo "(Done getting static page(s))"
        crystallize *.warc.gz
    else
        echo "WARNING: Could not download all static page(s), using cached copies as needed"
        rsync -av --checksum --progress --no-i-r --ignore-existing ../.futuramerlin-web-toolkit/gen/static/content/* .
    fi
)
set -e
mkdir -pv .futuramerlin-web-toolkit/gen/static/
rsync -av --checksum --progress --no-i-r content .futuramerlin-web-toolkit/gen/static/
