#!/bin/bash
# Futuramerlin Web Toolkit Content Generator: Static copy of page
wget --adjust-extension -p -e robots="off" "$@" || echo "WARNING: Wget reported non-zero exit status for static page download"
