#!/usr/bin/env bash
# Futuramerlin Web Toolkit Content Generator: Static copy of site directory
set -e
mkdir -pv content
(
    cd content
    set +e
    if wget --adjust-extension -p -e robots="off" --mirror --no-parent --warc-file="futuramerlin-web-toolkit.static-mirror.warc.gz" "$@"; then
        echo "(Done getting static page(s))"
        crystallize *.warc.gz
    else
        echo "WARNING: Could not download all static site(s), using cached copies as needed"
        rsync -av --checksum --progress --no-i-r --ignore-existing ../.futuramerlin-web-toolkit/gen/static/content/* .
    fi
)
set -e
mkdir -pv .futuramerlin-web-toolkit/gen/static/
rsync -av --checksum --progress --no-i-r content .futuramerlin-web-toolkit/gen/static/
