#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

set -x

pwd
cd "$(dirname "$(readlink -f "$1")")"
pwd
futuramerlin-web-toolkit-build-discography
