#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

finish() {
    (
        if [[ -e "${tempDir:?}" ]]; then
            rm -r "${tempDir:?}"
        fi
    )
}
trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."; finish; exit 1' ERR
trap finish EXIT

destDir="$(dirname "$(readlink -f "$1")")"
tempDir="$(tempDir)"
futuramerlin-web-toolkit-build-discography "$destDir" "$tempDir"
rm -r "$destDir"
mv "$tempDir" "$destDir"

finish
