#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

bookConf="fmwtk-book.conf"
if [[ -n "$1" ]]; then
    bookConf="$(basename "$(readlink -f "$1")")"
    shift
else
    bookConf="$(basename "$(readlink -f "$bookConf")")"
fi

cd "$(dirname "$bookConf")" || die "cd failed"

bookName="${bookConf/-fmwtk-book.conf}"

rm -rf "$bookName.fmwtk-book"
mkdir "$bookName.fmwtk-book"

targets=(html)
targetCount="${#targets[@]}"
for (( i=0; i<targetCount; i++ )); do
    target="${targets[$i]}"
    out="$bookName.fmwtk-book/$bookName-book-$(emdate).$target"
    touch "$out"

    while IFS= read -r -d '' currentPageLine; do
        depth="${currentPageLine/ *}"
        in="${currentPageLine#* }"
        if [[ "$depth" == "-1" ]]; then
            cat "$currentPageLine.$target" >> "$out"
        else
            htmlHeadingDepth=$((depth + 1))
            tempFile="$(tempFile)"
            cp "$in" "$tempFile"
            # Extract the title. Based on futuramerlin-web-toolkit-build-page
            perl -ni -e 'print, exit if s/(<h1>(((?!<\/h1>)[\S\s])*)<\/h1>)/\1/sg' "$tempFile"
            perl -0777 -p -i -e 's/^\s*//;s/\s*$//;' "$tempFile"
            ereplaceRegEx '<h1>(((?!<\/h1>)[\S\s])*)<\/h1>' '\1' "$tempFile"
            ereplaceRegEx '(?i)<[^>]*>' ' ' "$tempFile"
            ereplaceRegEx '\s+' ' ' "$tempFile"
            ereplaceRegEx '^\s+' '' "$tempFile"
            ereplaceRegEx '\s+$' '' "$tempFile"
            # Got the title
            title="$(cat "$tempFile")"
            echo "<h$htmlHeadingDepth>$title</h$htmlHeadingDepth>" >> "$out"
            cp "$in" "$tempFile"
            perl -0777 -p -i -e 's/<\/p>/\t/;' "$tempFile"
            cut "$tempFile" -f 1
        fi
    done < "$bookConf"

    echo '<html><head><meta http-equiv="Redirect:'"$out"'"><title></title></head><body></body></html>' > "$bookName.fmwtk-book/$bookName-book.$target"
done
