#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

set -x

sourceDir="$(readlink -f "$1")"

destDir="$(readlink -f "$2")"

maxPostsPerPage="5"

[[ -e "$destDir" ]] && rm -r "$destDir"

rsync -a --checksum "$sourceDir/" "$destDir"

cd "$destDir" || die

# Count the number of posts

numPosts="$(find "$destDir" -type f -print . | wc -c)"



echo "built" > ".futuramerlin-web-toolkit-blog.conf"
