#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

set -x

sourceDir="$(readlink -f "$1")"

destDir="$(readlink -f "$2")"

maxPostsPerPage="5"

[[ -e "$destDir" ]] && rm -r "$destDir"

rsync -a --checksum "$sourceDir/" "$destDir"

cd "$destDir" || die

# Count the number of posts

numPosts="$(find "$destDir" -type f -name "*.htm" -printf '.' | wc -c)"

makeIndexPage() {
    # Create redirect page
    mkdir "$currentPageNumber"
    if [[ "$currentPageNumber" == "1" ]]; then
        echo '<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="refresh" content="0; url=../"> </head> <body> </body> </html>' > "$currentPageNumber/index.html"
    else
        echo '<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="refresh" content="0; url=../page-'"$currentPageNumber"'.htm"> </head> <body> </body> </html>' > "$currentPageNumber/index.html"
    fi
    
    # Create actual index page
    if [[ "$currentPageNumber" == "1" ]]; then
    printf '%s\n\n' '<h1 class="title">Ember Blog</h1>' > 
}

if [[ "$numPosts" -gt "$maxPostsPerPage" ]]; then
    numPostsRemaining="$numPosts"
    currentPageNumber="1"
    while [[ "$numPostsRemaining" -gt "$maxPostsPerPage" ]]; do
        makeIndexPage
        numPostsRemaining=$(( numPostsRemaining - 5 ))
        currentPageNumber=$(( currentPageNumber + 1 ))
    done
    # Last (or only) page
    makeIndexPage
fi


echo "built" > ".futuramerlin-web-toolkit-blog.conf"
