#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

# set -x

cd tests || die

runTest() {
    testName="$1"
    if [[ -d "$testName" ]]; then
        cd "$testName" || die
        chmod +x ./exec
        ./exec
    elif [[ -f "$testName" ]]; then
        chmod +x ./"$testName"
        ./"$testName"
    fi
}

runTest blog
runTest blog-1page
